"""PlatformIO pre-build script — generates include/version.h from git.

Runs before every `pio run` invocation and writes firmware identity macros
(version, commit hash, dirty flag, build date) derived from the current git
state. The generated file is gitignored — git tags are the source of truth.

Macros exposed to C/C++:
    FW_VERSION      — string, e.g. "v1.2.0" or "v1.2.0-3-gabc123-dirty"
    FW_GIT_COMMIT   — short commit hash, e.g. "abc123d"
    FW_GIT_DIRTY    — 0 or 1 (uncommitted changes in working tree)
    FW_BUILD_DATE   — ISO date, e.g. "2026-04-18" (UTC)

Fallback when git is unavailable (e.g. source tarball): FW_VERSION is set to
"v0.0.0-nogit" so the firmware still compiles.
"""

import subprocess
from datetime import datetime, timezone
from pathlib import Path

Import("env")  # noqa: F821 — injected by PlatformIO SCons environment


def _run_git(args: list[str]) -> str | None:
    """Run a git command and return stripped stdout, or None on any failure."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=env["PROJECT_DIR"],  # noqa: F821
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _collect_version_info() -> dict[str, str | int]:
    describe = _run_git(
        ["describe", "--tags", "--always", "--dirty", "--match", "v[0-9]*"]
    )
    commit = _run_git(["rev-parse", "--short", "HEAD"])
    build_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    if describe is None:
        # Not a git repo or git not installed — ship a sentinel value
        return {
            "version": "v0.0.0-nogit",
            "commit": "unknown",
            "dirty": 0,
            "date": build_date,
        }

    dirty = 1 if describe.endswith("-dirty") else 0

    # `git describe` returns the short hash alone when no tag exists yet.
    # Prefix it so the macro is always a well-formed pseudo-version.
    if commit and describe == commit:
        version = f"v0.0.0-g{commit}"
    elif commit and describe == f"{commit}-dirty":
        version = f"v0.0.0-g{commit}-dirty"
    else:
        version = describe

    return {
        "version": version,
        "commit": commit or "unknown",
        "dirty": dirty,
        "date": build_date,
    }


def _render_header(info: dict[str, str | int]) -> str:
    return (
        "// Auto-generated by scripts/version.py at build time. DO NOT EDIT.\n"
        "// DO NOT COMMIT — this file is listed in .gitignore.\n"
        "#pragma once\n"
        "\n"
        f'#define FW_VERSION    "{info["version"]}"\n'
        f'#define FW_GIT_COMMIT "{info["commit"]}"\n'
        f"#define FW_GIT_DIRTY  {info['dirty']}\n"
        f'#define FW_BUILD_DATE "{info["date"]}"\n'
    )


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


info = _collect_version_info()
header_path = Path(env["PROJECT_DIR"]) / "include" / "version.h"  # noqa: F821
changed = _write_if_changed(header_path, _render_header(info))

marker = "updated" if changed else "unchanged"
print(
    f"version.py: FW_VERSION={info['version']} "
    f"commit={info['commit']} dirty={info['dirty']} ({marker})"
)
