// ============================================================================
// Digital Radio Receiver Firmware — OLED variant (env:esp32dev)
// Hardware: ESP32 + Si4732 + SSD1315 OLED (128x64) + Rotary Encoder
//
// Radio and encoder logic live in the shared modules radio.cpp / input.cpp so
// the TFT variant (env:esp32dev_tft, src/main_tft.cpp) can reuse them. Only
// the OLED-specific UI and the Arduino setup/loop entry points live here.
//
// The Si4732 RESET pin is NOT connected to the MCU — an external RC circuit
// handles hardware reset at power-on. See radio.cpp for the reset-less init
// sequence that replaces the library's GPIO-based flow.
// ============================================================================

#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#include "radio.h"
#include "input.h"

// Auto-generated by scripts/version.py before each build (gitignored).
// Provides FW_VERSION, FW_GIT_COMMIT, FW_GIT_DIRTY, FW_BUILD_DATE.
#include "version.h"

// ============================================================================
// Section 1: Pin Definitions & Constants
// ============================================================================

// --- I2C Bus (shared by OLED and Si4732) ---
constexpr uint8_t PIN_I2C_SDA = 21;
constexpr uint8_t PIN_I2C_SCL = 22;

// --- OLED Display ---
constexpr uint8_t SCREEN_WIDTH   = 128;
constexpr uint8_t SCREEN_HEIGHT  = 64;
constexpr uint8_t OLED_I2C_ADDR  = 0x3C;  // Typical address for SSD1315/SSD1306

// --- Firmware identity ---
// Embedded in the binary for inventory / forensic identification. Not rendered
// on OLED or printed to Serial by design — readable only via binary inspection:
//   strings .pio/build/esp32dev/firmware.elf | grep FW=
// `used` keeps the symbol in the object file; a no-op inline asm reference in
// setup() keeps it alive through the linker's --gc-sections pass.
extern "C" __attribute__((used)) const char FW_IDENTITY[] =
    "FW=" FW_VERSION " commit=" FW_GIT_COMMIT " built=" FW_BUILD_DATE;

// ============================================================================
// Section 2: Globals & State
// ============================================================================

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

static AdjustMode currentMode        = MODE_FREQUENCY;
static bool       displayNeedsUpdate = true;

// ============================================================================
// Section 3: Forward Declarations
// ============================================================================

static void initDisplay();
static void handleEncoderRotation(long value);
static void toggleMode();
static void updateDisplay();

static void drawModeIndicator();
static void drawRSSIBar();
static void drawFrequency();
static void drawVolumeBar();

// ============================================================================
// Section 4: setup() / loop()
// ============================================================================

void setup() {
    // No-op reference to the firmware identity string. `__attribute__((used))`
    // alone is not enough against the linker's --gc-sections pass; an inline
    // asm input constraint forces the symbol to be retained so the
    // "FW=...commit=...built=..." bytes survive in flash for post-mortem
    // inspection (`strings firmware.elf | grep FW=`).
    asm volatile("" : : "r"(FW_IDENTITY));

    Serial.begin(115200);
    Serial.println(F("Digital Radio (OLED) — starting up..."));

    Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);

    // Wait for the Si4732 RC reset circuit to release the chip.
    delay(500);

    initDisplay();     // splash (radio is not yet up)
    radioInit();
    encoderInit();
    encoderSetBoundsForMode(currentMode, radioGetFrequency(), radioGetVolume());

    displayNeedsUpdate = true;
    Serial.println(F("Digital Radio (OLED) — ready."));
}

void loop() {
    long encValue;
    if (encoderPollRotation(encValue)) {
        handleEncoderRotation(encValue);
    }
    if (encoderPollButton()) {
        toggleMode();
    }
    if (radioPollSignal()) {
        displayNeedsUpdate = true;
    }
    updateDisplay();
}

// ============================================================================
// Section 5: Input Handling
// ============================================================================

static void handleEncoderRotation(long value) {
    if (currentMode == MODE_FREQUENCY) {
        uint16_t newFreq = (uint16_t)(value * FM_FREQ_STEP);
        if (newFreq < FM_FREQ_MIN) newFreq = FM_FREQ_MIN;
        if (newFreq > FM_FREQ_MAX) newFreq = FM_FREQ_MAX;
        if (newFreq != radioGetFrequency()) {
            radioSetFrequency(newFreq);
            displayNeedsUpdate = true;
        }
    } else {
        uint8_t newVol = (uint8_t)value;
        if (newVol > MAX_VOLUME) newVol = MAX_VOLUME;
        if (newVol != radioGetVolume()) {
            radioSetVolume(newVol);
            displayNeedsUpdate = true;
        }
    }
}

static void toggleMode() {
    currentMode = (currentMode == MODE_FREQUENCY) ? MODE_VOLUME : MODE_FREQUENCY;
    encoderSetBoundsForMode(currentMode, radioGetFrequency(), radioGetVolume());
    displayNeedsUpdate = true;

    Serial.print(F("Mode: "));
    Serial.println((currentMode == MODE_FREQUENCY) ? F("FREQUENCY") : F("VOLUME"));
}

// ============================================================================
// Section 6: Display
// ============================================================================

static void initDisplay() {
    if (!display.begin(SSD1306_SWITCHCAPVCC, OLED_I2C_ADDR)) {
        Serial.println(F("ERROR: SSD1306/SSD1315 display not found!"));
        while (true) { delay(1000); }  // Halt — cannot proceed without display
    }

    // Splash screen
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(2);
    display.setCursor(8, 4);
    display.print(F("Digital"));
    display.setCursor(20, 28);
    display.print(F("Radio"));
    display.setTextSize(1);
    display.setCursor(16, 52);
    display.print(F("Initializing..."));
    display.display();
}

// Layout (SSD1315: top ~16px yellow, bottom ~48px blue):
//
//   Y=0  | FM          [RSSI bar]     |  <- Yellow zone
//   Y=16 |----------------------------|
//        | > 102.4 MHz                |  <- Blue zone (frequency)
//        |                            |
//        | > Vol [========--] 30      |  <- Blue zone (volume)
static void updateDisplay() {
    if (!displayNeedsUpdate) return;
    displayNeedsUpdate = false;

    display.clearDisplay();

    drawModeIndicator();
    drawRSSIBar();
    drawFrequency();
    drawVolumeBar();

    display.display();
}

static void drawModeIndicator() {
    display.setTextSize(2);
    display.setTextColor(SSD1306_WHITE);
    display.setCursor(0, 0);
    display.print(F("FM"));
}

// RSSI range is 0..127 dBuV, but typical FM signals fall within 0..60.
static void drawRSSIBar() {
    constexpr int BAR_MAX_W = 50;
    constexpr int BAR_H     = 10;
    constexpr int BAR_X     = SCREEN_WIDTH - BAR_MAX_W - 4;
    constexpr int BAR_Y     = 3;

    int barWidth = map(constrain(radioGetRssi(), 0, 60), 0, 60, 0, BAR_MAX_W);

    display.fillRect(BAR_X, BAR_Y, barWidth, BAR_H, SSD1306_WHITE);
    display.drawRect(BAR_X, BAR_Y, BAR_MAX_W, BAR_H, SSD1306_WHITE);
}

static void drawFrequency() {
    constexpr int Y = 22;

    display.setTextColor(SSD1306_WHITE);

    // Active-mode arrow
    if (currentMode == MODE_FREQUENCY) {
        display.setTextSize(1);
        display.setCursor(0, Y + 4);
        display.print(F(">"));
    }

    display.setTextSize(2);
    display.setCursor(10, Y);

    uint16_t freq     = radioGetFrequency();
    uint16_t mhzWhole = freq / 100;
    uint8_t  mhzFrac  = (freq % 100) / 10;
    display.print(mhzWhole);
    display.print(F("."));
    display.print(mhzFrac);

    display.setTextSize(1);
    display.setCursor(display.getCursorX() + 2, Y + 8);
    display.print(F("MHz"));
}

static void drawVolumeBar() {
    constexpr int Y         = 52;
    constexpr int BAR_X     = 32;
    constexpr int BAR_MAX_W = 68;
    constexpr int BAR_H     = 8;

    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);

    if (currentMode == MODE_VOLUME) {
        display.setCursor(0, Y);
        display.print(F(">"));
    }

    display.setCursor(8, Y);
    display.print(F("Vol"));

    uint8_t vol = radioGetVolume();
    int barWidth = map(vol, 0, MAX_VOLUME, 0, BAR_MAX_W);
    display.fillRect(BAR_X, Y, barWidth, BAR_H, SSD1306_WHITE);
    display.drawRect(BAR_X, Y, BAR_MAX_W, BAR_H, SSD1306_WHITE);

    display.setCursor(BAR_X + BAR_MAX_W + 4, Y);
    display.print(vol);
}
